# This is a sample build configuration for other languages.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Dockerhub as your build environment
# image: docker-image:tag

pipelines:
  default:
    - step:
        script:
          - stack test